### ISSUE TITLE
Default domain is not shown in domain list until settings are saved

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/domain#13]
This is with the diff from #12 added.

**Steps to reproduce**

1. Disable and uninstall Domain Access (`domain`)
2. Enable it
3. Go to `admin/structure/domain`

**Expected result**
Current domain is populated as primary domain

**Actual result**
Domain list is empty although primary domain is visible on `admin/structure/domain/batch`

4. Go to `admin/structure/domain/settings`
5. Without changing anything, click `Save`
6. Go to `admin/structure/domain`

Primary domain is now listed here.

**Comment by sudipto68** [comment]
@yorkshire-pudding @stpaultim 
I could recreate this. I tried to debug, why this is happening and I found that these blocks of code(on domain.admin.inc file line number 57) are not running when we install the module.
``` php
while ($domain = $result->fetchAssoc()) {
    if(!empty(domain_api($domain))) {
      $domains[$domain['domain_id']] = domain_api($domain);
    }
  }
```

That's Why it is not getting the default domain in the list and goes to this code
``` php
if (empty($domains)) {
    $form['error'] = array(
      '#markup' => t('No domains have been configured. <a href="!url">Add a new domain</a>.', array('!url' => url('admin/structure/domain/create'))),
    );
    return $form;
  }
```


But When we save the settings page configuration then the above code `while ($domain = $result->fetchAssoc())` runs and we get the default domain in the domain list.

**Comment by stpaultim** [comment]
@yorkshire-pudding and @sudipto68 

I think that this problem was the result of some inaccurate default settings in default config file. See: https://github.com/backdrop-contrib/domain/issues/19

@yorkshire-pudding See if this is still a problem.

**Comment by yorkshire-pudding** [comment]
I think this is now fixed.
